/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BaconCashRequest = IDL.Record({
  'id' : IDL.Text,
  'user' : IDL.Principal,
  'completed' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const Category = IDL.Variant({
  'music' : IDL.Null,
  'adult' : IDL.Null,
  'gaming' : IDL.Null,
  'sports' : IDL.Null,
  'horror' : IDL.Null,
});
export const Channel = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'category' : Category,
  'streamUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'baconCashBalance' : IDL.Nat,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChannel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'deleteChannel' : IDL.Func([IDL.Text], [], []),
  'fulfillBaconCashRequest' : IDL.Func([IDL.Text], [], []),
  'getAllBaconCashRequests' : IDL.Func(
      [],
      [IDL.Vec(BaconCashRequest)],
      ['query'],
    ),
  'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([IDL.Text], [IDL.Opt(Channel)], ['query']),
  'getMyBaconCashRequests' : IDL.Func(
      [],
      [IDL.Vec(BaconCashRequest)],
      ['query'],
    ),
  'getMyChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestBaconCash' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChannel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BaconCashRequest = IDL.Record({
    'id' : IDL.Text,
    'user' : IDL.Principal,
    'completed' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'music' : IDL.Null,
    'adult' : IDL.Null,
    'gaming' : IDL.Null,
    'sports' : IDL.Null,
    'horror' : IDL.Null,
  });
  const Channel = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'category' : Category,
    'streamUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'baconCashBalance' : IDL.Nat,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChannel' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'deleteChannel' : IDL.Func([IDL.Text], [], []),
    'fulfillBaconCashRequest' : IDL.Func([IDL.Text], [], []),
    'getAllBaconCashRequests' : IDL.Func(
        [],
        [IDL.Vec(BaconCashRequest)],
        ['query'],
      ),
    'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([IDL.Text], [IDL.Opt(Channel)], ['query']),
    'getMyBaconCashRequests' : IDL.Func(
        [],
        [IDL.Vec(BaconCashRequest)],
        ['query'],
      ),
    'getMyChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestBaconCash' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChannel' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };