/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIMessage { 'isAI' : boolean, 'text' : string }
export interface BaconCashRequest {
  'id' : string,
  'user' : Principal,
  'completed' : boolean,
  'amount' : bigint,
}
export type Category = { 'djs' : null } |
  { 'irl' : null } |
  { 'music' : null } |
  { 'adult' : null } |
  { 'gaming' : null } |
  { 'audio_video_podcasts' : null } |
  { 'sports' : null } |
  { 'horror' : null } |
  { 'ppv_events' : null } |
  { 'radio' : null };
export interface Channel {
  'id' : string,
  'title' : string,
  'thumbnail' : ExternalBlob,
  'owner' : Principal,
  'description' : string,
  'category' : Category,
  'streamKey' : string,
  'streamUrl' : string,
  'ingestUrl' : string,
}
export interface ChatMessage {
  'id' : bigint,
  'sender' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'senderName' : string,
}
export interface Conversation {
  'id' : string,
  'messages' : Array<AIMessage>,
  'owner' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface UserProfile {
  'baconCashBalance' : bigint,
  'name' : string,
  'bestScore' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChannel' : ActorMethod<
    [string, string, string, string, ExternalBlob, string, string, string],
    undefined
  >,
  'createChatRoom' : ActorMethod<[string], string>,
  'createDefaultChatRoom' : ActorMethod<[], string>,
  'deleteChannel' : ActorMethod<[string], undefined>,
  'fulfillBaconCashRequest' : ActorMethod<[string], undefined>,
  'getAllBaconCashRequests' : ActorMethod<[], Array<BaconCashRequest>>,
  'getAllChannels' : ActorMethod<[], Array<Channel>>,
  'getAllChatRooms' : ActorMethod<[], Array<[string, string]>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getBestScore' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[string], [] | [Channel]>,
  'getChatRoomMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getConversation' : ActorMethod<[string], [] | [Conversation]>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getMyBaconCashRequests' : ActorMethod<[], Array<BaconCashRequest>>,
  'getMyChannels' : ActorMethod<[], Array<Channel>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postMessage' : ActorMethod<[string, string, string], undefined>,
  'requestBaconCash' : ActorMethod<[bigint], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'storeConversation' : ActorMethod<[string, Conversation], undefined>,
  'updateBestScore' : ActorMethod<[bigint], undefined>,
  'updateChannel' : ActorMethod<
    [string, string, string, string, ExternalBlob, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];