/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BaconCashRequest = IDL.Record({
  'id' : IDL.Text,
  'user' : IDL.Principal,
  'completed' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const Category = IDL.Variant({
  'djs' : IDL.Null,
  'irl' : IDL.Null,
  'music' : IDL.Null,
  'adult' : IDL.Null,
  'gaming' : IDL.Null,
  'audio_video_podcasts' : IDL.Null,
  'sports' : IDL.Null,
  'horror' : IDL.Null,
  'ppv_events' : IDL.Null,
  'radio' : IDL.Null,
});
export const Channel = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'chatRoomId' : IDL.Opt(IDL.Text),
  'category' : Category,
  'streamKey' : IDL.Text,
  'streamUrl' : IDL.Text,
  'ingestUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'baconCashBalance' : IDL.Nat,
  'name' : IDL.Text,
  'bestScore' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
});
export const AIMessage = IDL.Record({ 'isAI' : IDL.Bool, 'text' : IDL.Text });
export const Conversation = IDL.Record({
  'id' : IDL.Text,
  'messages' : IDL.Vec(AIMessage),
  'owner' : IDL.Principal,
});
export const StreamerPayment = IDL.Record({
  'id' : IDL.Text,
  'channelId' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChannel' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createChatRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createDefaultChatRoom' : IDL.Func([], [IDL.Text], []),
  'deleteChannel' : IDL.Func([IDL.Text], [], []),
  'fulfillBaconCashRequest' : IDL.Func([IDL.Text], [], []),
  'getAllBaconCashRequests' : IDL.Func(
      [],
      [IDL.Vec(BaconCashRequest)],
      ['query'],
    ),
  'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getAllChatRooms' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getBestScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([IDL.Text], [IDL.Opt(Channel)], ['query']),
  'getChatRoomMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getConversation' : IDL.Func([IDL.Text], [IDL.Opt(Conversation)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getMyBaconCashRequests' : IDL.Func(
      [],
      [IDL.Vec(BaconCashRequest)],
      ['query'],
    ),
  'getMyChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getPaymentsReceived' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StreamerPayment)],
      ['query'],
    ),
  'getPaymentsSent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StreamerPayment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'requestBaconCash' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendTip' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'storeConversation' : IDL.Func([IDL.Text, Conversation], [], []),
  'updateBestScore' : IDL.Func([IDL.Nat], [], []),
  'updateChannel' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BaconCashRequest = IDL.Record({
    'id' : IDL.Text,
    'user' : IDL.Principal,
    'completed' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'djs' : IDL.Null,
    'irl' : IDL.Null,
    'music' : IDL.Null,
    'adult' : IDL.Null,
    'gaming' : IDL.Null,
    'audio_video_podcasts' : IDL.Null,
    'sports' : IDL.Null,
    'horror' : IDL.Null,
    'ppv_events' : IDL.Null,
    'radio' : IDL.Null,
  });
  const Channel = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'chatRoomId' : IDL.Opt(IDL.Text),
    'category' : Category,
    'streamKey' : IDL.Text,
    'streamUrl' : IDL.Text,
    'ingestUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'baconCashBalance' : IDL.Nat,
    'name' : IDL.Text,
    'bestScore' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
  });
  const AIMessage = IDL.Record({ 'isAI' : IDL.Bool, 'text' : IDL.Text });
  const Conversation = IDL.Record({
    'id' : IDL.Text,
    'messages' : IDL.Vec(AIMessage),
    'owner' : IDL.Principal,
  });
  const StreamerPayment = IDL.Record({
    'id' : IDL.Text,
    'channelId' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChannel' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createChatRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createDefaultChatRoom' : IDL.Func([], [IDL.Text], []),
    'deleteChannel' : IDL.Func([IDL.Text], [], []),
    'fulfillBaconCashRequest' : IDL.Func([IDL.Text], [], []),
    'getAllBaconCashRequests' : IDL.Func(
        [],
        [IDL.Vec(BaconCashRequest)],
        ['query'],
      ),
    'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getAllChatRooms' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getBestScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([IDL.Text], [IDL.Opt(Channel)], ['query']),
    'getChatRoomMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getConversation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getMyBaconCashRequests' : IDL.Func(
        [],
        [IDL.Vec(BaconCashRequest)],
        ['query'],
      ),
    'getMyChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getPaymentsReceived' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StreamerPayment)],
        ['query'],
      ),
    'getPaymentsSent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StreamerPayment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'requestBaconCash' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendTip' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'storeConversation' : IDL.Func([IDL.Text, Conversation], [], []),
    'updateBestScore' : IDL.Func([IDL.Nat], [], []),
    'updateChannel' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };