/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BaconCashRequest {
    id: string;
    user: Principal;
    completed: boolean;
    amount: bigint;
}
export interface AIMessage {
    isAI: boolean;
    text: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ChatMessage {
    id: bigint;
    sender: Principal;
    message: string;
    timestamp: bigint;
    senderName: string;
}
export interface StreamerPayment {
    id: string;
    channelId: string;
    recipient: Principal;
    sender: Principal;
    message?: string;
    timestamp: bigint;
    amount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Channel {
    id: string;
    title: string;
    thumbnail: ExternalBlob;
    owner: Principal;
    description: string;
    chatRoomId?: string;
    category: Category;
    streamKey: string;
    streamUrl: string;
    ingestUrl: string;
}
export interface Conversation {
    id: string;
    messages: Array<AIMessage>;
    owner: Principal;
}
export interface UserProfile {
    baconCashBalance: bigint;
    name: string;
    bestScore: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    djs = "djs",
    irl = "irl",
    music = "music",
    adult = "adult",
    gaming = "gaming",
    audio_video_podcasts = "audio_video_podcasts",
    sports = "sports",
    horror = "horror",
    ppv_events = "ppv_events",
    radio = "radio"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChannel(id: string, title: string, category: string, description: string, thumbnail: ExternalBlob, streamUrl: string, ingestUrl: string, streamKey: string): Promise<string>;
    createChatRoom(name: string): Promise<string>;
    createDefaultChatRoom(): Promise<string>;
    deleteChannel(id: string): Promise<void>;
    fulfillBaconCashRequest(requestId: string): Promise<void>;
    getAllBaconCashRequests(): Promise<Array<BaconCashRequest>>;
    getAllChannels(): Promise<Array<Channel>>;
    getAllChatRooms(): Promise<Array<[string, string]>>;
    getBalance(): Promise<bigint>;
    getBestScore(): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannel(id: string): Promise<Channel | null>;
    getChatRoomMessages(roomId: string): Promise<Array<ChatMessage>>;
    getConversation(conversationId: string): Promise<Conversation | null>;
    getConversations(): Promise<Array<Conversation>>;
    getMyBaconCashRequests(): Promise<Array<BaconCashRequest>>;
    getMyChannels(): Promise<Array<Channel>>;
    getPaymentsReceived(user: Principal): Promise<Array<StreamerPayment>>;
    getPaymentsSent(user: Principal): Promise<Array<StreamerPayment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    postMessage(roomId: string, senderName: string, message: string): Promise<void>;
    requestBaconCash(amount: bigint): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendTip(sender: Principal, recipient: Principal, channelId: string, amount: bigint, message: string | null): Promise<string>;
    storeConversation(conversationId: string, conversation: Conversation): Promise<void>;
    updateBestScore(score: bigint): Promise<void>;
    updateChannel(id: string, title: string, category: string, description: string, thumbnail: ExternalBlob, streamUrl: string, ingestUrl: string, streamKey: string): Promise<void>;
}
import type { Category as _Category, Channel as _Channel, Conversation as _Conversation, ExternalBlob as _ExternalBlob, StreamerPayment as _StreamerPayment, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChannel(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob, arg5: string, arg6: string, arg7: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createChannel(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChannel(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
            return result;
        }
    }
    async createChatRoom(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatRoom(arg0);
            return result;
        }
    }
    async createDefaultChatRoom(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDefaultChatRoom();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDefaultChatRoom();
            return result;
        }
    }
    async deleteChannel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannel(arg0);
            return result;
        }
    }
    async fulfillBaconCashRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fulfillBaconCashRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fulfillBaconCashRequest(arg0);
            return result;
        }
    }
    async getAllBaconCashRequests(): Promise<Array<BaconCashRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBaconCashRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBaconCashRequests();
            return result;
        }
    }
    async getAllChannels(): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChannels();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChannels();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllChatRooms(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChatRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChatRooms();
            return result;
        }
    }
    async getBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getBestScore(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestScore();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannel(arg0: string): Promise<Channel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannel(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannel(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatRoomMessages(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatRoomMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatRoomMessages(arg0);
            return result;
        }
    }
    async getConversation(arg0: string): Promise<Conversation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getMyBaconCashRequests(): Promise<Array<BaconCashRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBaconCashRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBaconCashRequests();
            return result;
        }
    }
    async getMyChannels(): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyChannels();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyChannels();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsReceived(arg0: Principal): Promise<Array<StreamerPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsReceived(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsReceived(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsSent(arg0: Principal): Promise<Array<StreamerPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsSent(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsSent(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async postMessage(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async requestBaconCash(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestBaconCash(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestBaconCash(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendTip(arg0: Principal, arg1: Principal, arg2: string, arg3: bigint, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTip(arg0, arg1, arg2, arg3, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTip(arg0, arg1, arg2, arg3, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async storeConversation(arg0: string, arg1: Conversation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeConversation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeConversation(arg0, arg1);
            return result;
        }
    }
    async updateBestScore(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBestScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBestScore(arg0);
            return result;
        }
    }
    async updateChannel(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChannel(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChannel(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
            return result;
        }
    }
}
function from_candid_Category_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_Channel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Channel): Promise<Channel> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_StreamerPayment_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreamerPayment): StreamerPayment {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Channel]): Promise<Channel | null> {
    return value.length === 0 ? null : await from_candid_Channel_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Conversation]): Conversation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    thumbnail: _ExternalBlob;
    owner: Principal;
    description: string;
    chatRoomId: [] | [string];
    category: _Category;
    streamKey: string;
    streamUrl: string;
    ingestUrl: string;
}): Promise<{
    id: string;
    title: string;
    thumbnail: ExternalBlob;
    owner: Principal;
    description: string;
    chatRoomId?: string;
    category: Category;
    streamKey: string;
    streamUrl: string;
    ingestUrl: string;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.thumbnail),
        owner: value.owner,
        description: value.description,
        chatRoomId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.chatRoomId)),
        category: from_candid_Category_n16(_uploadFile, _downloadFile, value.category),
        streamKey: value.streamKey,
        streamUrl: value.streamUrl,
        ingestUrl: value.ingestUrl
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    channelId: string;
    recipient: Principal;
    sender: Principal;
    message: [] | [string];
    timestamp: bigint;
    amount: bigint;
}): {
    id: string;
    channelId: string;
    recipient: Principal;
    sender: Principal;
    message?: string;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        channelId: value.channelId,
        recipient: value.recipient,
        sender: value.sender,
        message: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.message)),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    djs: null;
} | {
    irl: null;
} | {
    music: null;
} | {
    adult: null;
} | {
    gaming: null;
} | {
    audio_video_podcasts: null;
} | {
    sports: null;
} | {
    horror: null;
} | {
    ppv_events: null;
} | {
    radio: null;
}): Category {
    return "djs" in value ? Category.djs : "irl" in value ? Category.irl : "music" in value ? Category.music : "adult" in value ? Category.adult : "gaming" in value ? Category.gaming : "audio_video_podcasts" in value ? Category.audio_video_podcasts : "sports" in value ? Category.sports : "horror" in value ? Category.horror : "ppv_events" in value ? Category.ppv_events : "radio" in value ? Category.radio : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Channel>): Promise<Array<Channel>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Channel_n12(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StreamerPayment>): Array<StreamerPayment> {
    return value.map((x)=>from_candid_StreamerPayment_n24(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
